version: '3'

services:
  mongodb:
    image: bitnami/mongodb:latest
    restart: unless-stopped
    environment:
      - MONGODB_ROOT_PASSWORD=topsecret
    ports:
      - 27017:27017

  redis:
    image: redis/redis-stack
    restart: unless-stopped
    ports:
      - 6379:6379
      - 8001:8001
    environment:
      REDIS_ARGS: --save 60 1 --notify-keyspace-events KEA
