# 1. Регистрируем нового пользователя
POST http://localhost:8080/users/
Content-Type: application/json

{
  "name": "user-one",
  "password": "topsecret",
  "email": "serge.kutin@gmail.com"
}

###

# 2. Получаем токен авторизации для пользователя
POST http://localhost:8080/login
Content-Type: application/json

{
    "id": "<ID из ответа на запрос 1>",
    "password": "topsecret"
}

###

#  3. Создаем лицензии для пользователя (выполняем несколько раз)
POST http://localhost:8080/users/<ID из ответа на запрос 1>/licenses/
Authorization: Bearer <Токен из ответа на запрос 2>
Content-Type: application/json

{
  "name": "some license",
  "expires": "2024-01-01"
}

###

# 4. Получаем лицензии пользователя
GET http://localhost:8080/users/<ID из ответа на запрос 1>/licenses/
Authorization: Bearer <Токен из ответа на запрос 2>

###

